--------------------------------------------------------------------------------
---------------------------------- DokusCore -----------------------------------
--------------------------------------------------------------------------------
-- https://github.com/DokusCore/DokusCore--Stables
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
_Stables = {

  Dialogs = {
    { ID = 'Valentine',   Welcome = true, Goodbye = true },
  },

  Blips = {
    { ID = 'Valentine', Coords = vec3(-367.73, 787.72, 116.26) },
  },

  NPCs = {
    {
      ID = 'Valentine',
      NPCTakesHorse = true,
      Coords = vec3(-364.4, 791.8, 115.1),
      CamPos = { Coords = vec3(-367.73, 787.72, 116.26), Heading = 182.3 },
      OffSet = { 0.5, -1.5, 0.5 },
      Heading = 133.8,
      Radius = { 20.0, 5.0, 3.0 },
      Hash = 'U_M_M_BwmStablehand_01'
    },
    {
      ID = 'Saint Denis',
      NPCTakesHorse = false,
      Coords = vec3(2512.3, -1456.8, 45.3),
      CamPos = { Coords = vec3(2505.1, -1450.5, 46.5), Heading = 260.1 },
      OffSet = { 0.5, -1.5, 0.5 },
      Heading = 89.9,
      Radius = { 20.0, 5.0, 3.0 },
      Hash = 'U_M_M_BwmStablehand_01'
    },
    {
      ID = 'Berry Creek',
      NPCTakesHorse = true,
      Coords = vec3(1211.0, -191.0, 101.3),
      CamPos = { Coords = vec3(1205.5, -188.0, 101.4), Heading = 110.0 },
      OffSet = { 0.5, -1.5, 0.5 },
      Heading = 111.4,
      Radius = { 20.0, 5.0, 3.0 },
      Hash = 'U_M_M_BwmStablehand_01'
    }
  },

  Horse = {
    Call   = { Radius = 100.0, Speed = 2.0, Dist = 5.0 },
    Follow = { Radius = 30.0,  Speed = 1.0 },
  },

  HorsePos = {
    { ID = 'Valentine',   Coords = vec3(-366.3, 782.0, 116.1),  Heading = 343.5 },
    { ID = 'Saint Denis', Coords = vec3(2508.5, -1453.2, 45.4), Heading = 114.6 },
    { ID = 'Berry Creek', Coords = vec3(1204.1, -193.0, 101.4), Heading = 285.0 },
  },

  HorseSpawn = {
    { ID = 'Valentine',   Coords = vec3(-388.9, 785.8, 115.8),  Heading = 272.8 },
    { ID = 'Saint Denis', Coords = vec3(2511.1, -1453.0, 46.4), Heading = 112.6 },
    { ID = 'Berry Creek', Coords = vec3(1205.4, -205.7, 101.2), Heading = 279.6 },
  },

  HorseDrop = {
    { ID = 'Valentine', Coords = vec3(-388.9, 785.8, 115.8)  },
    { ID = 'Berry Creek', Coords = vec3(1205.4, -205.7, 101.2) },
  },

  HorseDecoys ={
    { ID = 'Valentine', Main = false, Coords = vec3(-363.0, 781.8, 116.1), Heading = 27.1  },
    { ID = 'Valentine', Main = false, Coords = vec3(-369.0, 781.6, 116.1), Heading = 5.4   },
    { ID = 'Valentine', Main = false, Coords = vec3(-371.6, 781.0, 116.1), Heading = 4.7   },
    { ID = 'Valentine', Main = false, Coords = vec3(-374.7, 781.0, 116.1), Heading = 0.5   },
    { ID = 'Valentine', Main = false, Coords = vec3(-369.6, 791.9, 116.1), Heading = 185.0 },
    { ID = 'Valentine', Main = false, Coords = vec3(-372.8, 792.2, 116.1), Heading = 204.6 },
    { ID = 'Valentine', Main = false, Coords = vec3(-375.6, 791.9, 116.1), Heading = 200.6 },
    { ID = 'Valentine', Main = true,  Coords = vec3(-366.3, 782.0, 116.1), Heading = 343.5 },
  },


  RandomDecoys = {
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_Greyovero' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_SplashedWhite' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_Tobiano' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_piebald' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_splashedpiebald' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_Buckskin' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_SilverTailBuckskin' },
    { ID = 'Valentine', Model = 'A_C_Horse_Belgian_MealyChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_HungarianHalfbred_DarkDappleGrey' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_Black' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_White' },
    { ID = 'Valentine', Model = 'A_C_Horse_MissouriFoxTrotter_SableChampagne' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_Greyovero' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_Overo' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_SplashedWhite' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanPaint_Tobiano' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_palominoblagdon' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_piebald' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_splashedbay' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_splashedpiebald' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_skewbald' },
    { ID = 'Valentine', Model = 'a_c_horse_gypsycob_whiteblagdon' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_Black' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_Buckskin' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_PalominoDapple' },
    { ID = 'Valentine', Model = 'A_C_Horse_AmericanStandardbred_SilverTailBuckskin' },
    { ID = 'Valentine', Model = 'A_C_Horse_Andalusian_DarkBay' },
    { ID = 'Valentine', Model = 'A_C_Horse_Andalusian_Perlino' },
    { ID = 'Valentine', Model = 'A_C_Horse_Andalusian_RoseGray' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_BlackSnowflake' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_Blanket' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_BrownLeopard' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_FewSpotted_PC' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_Leopard' },
    { ID = 'Valentine', Model = 'A_C_Horse_Appaloosa_LeopardBlanket' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_Black' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_Grey' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_RedChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_RoseGreyBay' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_WarpedBrindle_PC' },
    { ID = 'Valentine', Model = 'A_C_Horse_Arabian_White' },
    { ID = 'Valentine', Model = 'A_C_Horse_Ardennes_BayRoan' },
    { ID = 'Valentine', Model = 'A_C_Horse_Ardennes_IronGreyRoan' },
    { ID = 'Valentine', Model = 'A_C_Horse_Ardennes_StrawberryRoan' },
    { ID = 'Valentine', Model = 'A_C_Horse_Belgian_BlondChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_Belgian_MealyChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_DutchWarmblood_ChocolateRoan' },
    { ID = 'Valentine', Model = 'A_C_Horse_DutchWarmblood_SealBrown' },
    { ID = 'Valentine', Model = 'A_C_Horse_DutchWarmblood_SootyBuckskin' },
    { ID = 'Valentine', Model = 'A_C_Horse_HungarianHalfbred_DarkDappleGrey' },
    { ID = 'Valentine', Model = 'A_C_Horse_HungarianHalfbred_FlaxenChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_HungarianHalfbred_LiverChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_HungarianHalfbred_PiebaldTobiano' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_Black' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_ChestnutPinto' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_Grey' },
    { ID = 'Valentine', Model = 'A_C_Horse_KentuckySaddle_SilverBay' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_Black' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_Silver' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_Cremello' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_Grey' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_DappleRoseGrey' },
    { ID = 'Valentine', Model = 'A_C_Horse_Kladruber_White' },
    { ID = 'Valentine', Model = 'A_C_Horse_MissouriFoxTrotter_AmberChampagne' },
    { ID = 'Valentine', Model = 'A_C_Horse_MissouriFoxTrotter_SableChampagne' },
    { ID = 'Valentine', Model = 'A_C_Horse_MissouriFoxTrotter_SilverDapplePinto' },
    { ID = 'Valentine', Model = 'a_c_horse_missourifoxtrotter_blacktovero' },
    { ID = 'Valentine', Model = 'a_c_horse_missourifoxtrotter_blueroan' },
    { ID = 'Valentine', Model = 'a_c_horse_missourifoxtrotter_buckskinbrindle' },
    { ID = 'Valentine', Model = 'a_c_horse_missourifoxtrotter_dapplegrey' },
    { ID = 'Valentine', Model = 'A_C_Horse_Morgan_Bay' },
    { ID = 'Valentine', Model = 'A_C_Horse_Morgan_BayRoan' },
    { ID = 'Valentine', Model = 'A_C_Horse_Morgan_FlaxenChestnut' },
    { ID = 'Valentine', Model = 'A_C_Horse_Morgan_LiverChestnut_PC' },
    { ID = 'Valentine', Model = 'A_C_Horse_Morgan_Palomino' },
    { ID = 'Valentine', Model = 'A_C_Horse_MP_Mangy_Backup' },
    { ID = 'Valentine', Model = 'A_C_Horse_Mustang_GoldenDun' },
    { ID = 'Valentine', Model = 'A_C_Horse_Mustang_GrulloDun' },
    { ID = 'Valentine', Model = 'A_C_Horse_Mustang_TigerStripedBay' },
    { ID = 'Valentine', Model = 'A_C_Horse_Mustang_WildBay' },
    { ID = 'Valentine', Model = 'a_c_horse_mustang_blackovero' },
    { ID = 'Valentine', Model = 'a_c_horse_mustang_buckskin' },
    { ID = 'Valentine', Model = 'a_c_horse_mustang_chestnuttovero' },
    { ID = 'Valentine', Model = 'a_c_horse_mustang_reddunovero' },
  },

  Horses = {
    {
  		name = "American Paint",
  		["A_C_Horse_AmericanPaint_Greyovero"]     = { Name = "Grey",        Price = 12.25 },
  		["A_C_Horse_AmericanPaint_Overo"]         = { Name = "Overo",       Price = 12.25 },
  		["A_C_Horse_AmericanPaint_SplashedWhite"] = { Name = "Splashwhite", Price = 12.25 },
  		["A_C_Horse_AmericanPaint_Tobiano"]       = { Name = "Tobiano",     Price = 12.25 },

  	},
  	{
  		name = "Gypsy Cob",
  		["a_c_horse_gypsycob_palominoblagdon"]    = { Name = "palominoblagdon", Price = 12.25 },
  		["a_c_horse_gypsycob_piebald"]            = { Name = "piebald",         Price = 12.25 },
  		["a_c_horse_gypsycob_splashedbay"]        = { Name = "splashedbay",     Price = 12.25 },
  		["a_c_horse_gypsycob_splashedpiebald"]    = { Name = "splashedpiebald", Price = 12.25 },
  		["a_c_horse_gypsycob_skewbald"]           = { Name = "skewbald",        Price = 12.25 },
  		["a_c_horse_gypsycob_whiteblagdon"]       = { Name = "whiteblagdon",    Price = 12.25 },
  	},
  	{
  		name = "American Standardbred",
  		["A_C_Horse_AmericanStandardbred_Black"]              = { Name = "Black",              Price = 12.25 },
  		["A_C_Horse_AmericanStandardbred_Buckskin"]           = { Name = "Buckskin",           Price = 12.25 },
  		["A_C_Horse_AmericanStandardbred_PalominoDapple"]     = { Name = "PalominoDapple",     Price = 12.25 },
  		["A_C_Horse_AmericanStandardbred_SilverTailBuckskin"] = { Name = "SilverTailBuckskin", Price = 12.25 },
  	},
  	{
  		name = "Andalusian",
  		["A_C_Horse_Andalusian_DarkBay"]  = { Name = "DarkBay", Price = 12.25 },
  		["A_C_Horse_Andalusian_Perlino"]  = { Name = "Perlino", Price = 12.25 },
  		["A_C_Horse_Andalusian_RoseGray"] = { Name = "RoseGray",Price = 12.25 },
  	},
  	{
  		name = "Appaloosa",
  		["A_C_Horse_Appaloosa_BlackSnowflake"] = { Name = "BlackSnowflake", Price = 12.25 },
  		["A_C_Horse_Appaloosa_Blanket"]        = { Name = "Blanket",        Price = 12.25 },
  		["A_C_Horse_Appaloosa_BrownLeopard"]   = { Name = "BrownLeopard",   Price = 12.25 },
  		["A_C_Horse_Appaloosa_FewSpotted_PC"]  = { Name = "FewSpotted_PC",  Price = 12.25 },
  		["A_C_Horse_Appaloosa_Leopard"]        = { Name = "Leopard",        Price = 12.25 },
  		["A_C_Horse_Appaloosa_LeopardBlanket"] = { Name = "LeopardBlanket", Price = 12.25 },
  	},
  	{
  		name = "Arabian",
  		["A_C_Horse_Arabian_Black"]            = { Name = "Black",         Price = 12.25 },
  		["A_C_Horse_Arabian_Grey"]             = { Name = "Grey",          Price = 12.25 },
  		["A_C_Horse_Arabian_RedChestnut"]      = { Name = "RedChestnut",   Price = 12.25 },
  		["A_C_Horse_Arabian_RoseGreyBay"]      = { Name = "RoseGreyBay",   Price = 12.25 },
  		["A_C_Horse_Arabian_WarpedBrindle_PC"] = { Name = "WarpedBrindle", Price = 12.25 },
  		["A_C_Horse_Arabian_White"]            = { Name = "White",         Price = 12.25 },

  	},
  	{
  		name = "Ardennes",
  		["A_C_Horse_Ardennes_BayRoan"]        = { Name = "BayRoan",        Price = 12.25 },
  		["A_C_Horse_Ardennes_IronGreyRoan"]   = { Name = "IronGreyRoan",   Price = 12.25 },
  		["A_C_Horse_Ardennes_StrawberryRoan"] = { Name = "StrawberryRoan", Price = 12.25 },
  	},
  	{
  		name = "Belgian",
  		["A_C_Horse_Belgian_BlondChestnut"] = { Name = "BlondChestnut", Price = 12.25 },
  		["A_C_Horse_Belgian_MealyChestnut"] = { Name = "MealyChestnut", Price = 12.25 },
  	},
  	{
  		name = "Dutch Warmblood",
  		["A_C_Horse_DutchWarmblood_ChocolateRoan"] = { Name = "ChocolateRoan", Price = 12.25 },
  		["A_C_Horse_DutchWarmblood_SealBrown"]     = { Name = "SealBrown",     Price = 12.25 },
  		["A_C_Horse_DutchWarmblood_SootyBuckskin"] = { Name = "SootyBuckskin", Price = 12.25 },
  	},
  	{
  		name = "Hungarian Halfbred",
  		["A_C_Horse_HungarianHalfbred_DarkDappleGrey"] = { Name = "DarkDappleGrey", Price = 12.25 },
  		["A_C_Horse_HungarianHalfbred_FlaxenChestnut"] = { Name = "FlaxenChestnut", Price = 12.25 },
  		["A_C_Horse_HungarianHalfbred_LiverChestnut"]  = { Name = "LiverChestnut",  Price = 12.25 },
  		["A_C_Horse_HungarianHalfbred_PiebaldTobiano"] = { Name = "PiebaldTobiano", Price = 12.25 },
  	},
  	{
  		name = "Kentucky Saddle",
  		["A_C_Horse_KentuckySaddle_Black"]                 = { Name = "Black",              Price = 12.25 },
  		["A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC"] = { Name = "ButterMilkBuckskin", Price = 12.25 },
  		["A_C_Horse_KentuckySaddle_ChestnutPinto"]         = { Name = "ChestnutPinto",      Price = 12.25 },
  		["A_C_Horse_KentuckySaddle_Grey"]                  = { Name = "Grey",               Price = 12.25 },
  		["A_C_Horse_KentuckySaddle_SilverBay"]             = { Name = "SilverBay",          Price = 12.25 },
  	},
  	{
  		name = "Kladruber",
  		["A_C_Horse_Kladruber_Black"]          = { Name = "Black",          Price = 12.25 },
  		["A_C_Horse_Kladruber_Silver"]         = { Name = "Silver",         Price = 12.25 },
  		["A_C_Horse_Kladruber_Cremello"]       = { Name = "Cremello",       Price = 12.25 },
  		["A_C_Horse_Kladruber_Grey"]           = { Name = "Grey",           Price = 12.25 },
  		["A_C_Horse_Kladruber_DappleRoseGrey"] = { Name = "DappleRoseGrey", Price = 12.25 },
  		["A_C_Horse_Kladruber_White"]          = { Name = "White",          Price = 12.25 },
  	},
  	{
  		name = "Missouri Fox Trotter",
  		["A_C_Horse_MissouriFoxTrotter_AmberChampagne"]    = { Name = "AmberChampagne",    Price = 12.25 },
  		["A_C_Horse_MissouriFoxTrotter_SableChampagne"]    = { Name = "SableChampagne",    Price = 12.25 },
  		["A_C_Horse_MissouriFoxTrotter_SilverDapplePinto"] = { Name = "SilverDapplePinto", Price = 12.25 },
      ["a_c_horse_missourifoxtrotter_blacktovero"]       = { Name = "black tovero",      Price = 12.25 },
      ["a_c_horse_missourifoxtrotter_blueroan"]          = { Name = "blue",              Price = 12.25 },
      ["a_c_horse_missourifoxtrotter_buckskinbrindle"]   = { Name = "buckskin",          Price = 12.25 },
      ["a_c_horse_missourifoxtrotter_dapplegrey"]        = { Name = "dapple grey",       Price = 12.25 },
  	},
  	{
  		name = "Morgan",
  		["A_C_Horse_Morgan_Bay"]              = { Name = "Bay",            Price = 12.25 },
  		["A_C_Horse_Morgan_BayRoan"]          = { Name = "BayRoan",        Price = 12.25 },
  		["A_C_Horse_Morgan_FlaxenChestnut"]   = { Name = "FlaxenChestnut", Price = 12.25 },
  		["A_C_Horse_Morgan_LiverChestnut_PC"] = { Name = "LiverChestnut",  Price = 12.25 },
  		["A_C_Horse_Morgan_Palomino"]         = { Name = "Palomino",       Price = 12.25 },
  	},
  	{
  		name = "Old Penco",
  		["A_C_Horse_MP_Mangy_Backup"]         = { Name = "Mangy", Price = 12.25 },
  	},
  	{
  		name = "Mustang",
  		["A_C_Horse_Mustang_GoldenDun"]       = { Name = "GoldenDun",       Price = 12.25 },
  		["A_C_Horse_Mustang_GrulloDun"]       = { Name = "GrulloDun",       Price = 12.25 },
  		["A_C_Horse_Mustang_TigerStripedBay"] = { Name = "TigerStripedBay", Price = 12.25 },
  		["A_C_Horse_Mustang_WildBay"]         = { Name = "WildBay",         Price = 12.25 },
  		["a_c_horse_mustang_blackovero"]      = { Name = "black overo",     Price = 12.25 },
      ["a_c_horse_mustang_buckskin"]        = { Name = "buck skin",       Price = 12.25 },
      ["a_c_horse_mustang_chestnuttovero"]  = { Name = "chestnutt",       Price = 12.25 },
      ["a_c_horse_mustang_reddunovero"]     = { Name = "red",             Price = 12.25 },
  	},
  	{
  		name = "Nokota",
  		["A_C_Horse_Nokota_BlueRoan"]          = { Name = "BlueRoan",          Price = 12.25 },
  		["A_C_Horse_Nokota_ReverseDappleRoan"] = { Name = "ReverseDappleRoan", Price = 12.25 },
  		["A_C_Horse_Nokota_WhiteRoan"]         = { Name = "WhiteRoan",         Price = 12.25 },
  	},
  	{
  		name = "Shire",
  		["A_C_Horse_Shire_DarkBay"]    = { Name = "DarkBay",    Price = 12.25 },
  		["A_C_Horse_Shire_LightGrey"]  = { Name = "LightGrey",  Price = 12.25 },
  		["A_C_Horse_Shire_RavenBlack"] = { Name = "RavenBlack", Price = 12.25 },
  	},
  	{
  		name = "Suffolk Punch",
  		["A_C_Horse_SuffolkPunch_RedChestnut"] = { Name = "RedChestnut", Price = 12.25 },
  		["A_C_Horse_SuffolkPunch_Sorrel"]      = { Name = "Sorrel",      Price = 12.25 },
  	},
  	{
  		name = "Tennessee Walker",
  		["A_C_Horse_TennesseeWalker_BlackRabicano"]   = { Name = "BlackRabicano", Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_Chestnut"]        = { Name = "Chestnut",      Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_DappleBay"]       = { Name = "DappleBay",     Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_FlaxenRoan"]      = { Name = "FlaxenRoan",    Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_MahoganyBay"]     = { Name = "MahoganyBay",   Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_RedRoan"]         = { Name = "RedRoan",       Price = 12.25 },
  		["A_C_Horse_TennesseeWalker_GoldPalomino_PC"] = { Name = "GoldPalomino",  Price = 12.25 },
  	},
  	{
  		name = "Thoroughbred",
  		["A_C_Horse_Thoroughbred_BlackChestnut"]      = { Name = "BlackChestnut",      Price = 12.25 },
  		["A_C_Horse_Thoroughbred_BloodBay"]           = { Name = "BloodBay",           Price = 12.25 },
  		["A_C_Horse_Thoroughbred_Brindle"]            = { Name = "Brindle",            Price = 12.25 },
  		["A_C_Horse_Thoroughbred_DappleGrey"]         = { Name = "DappleGrey",         Price = 12.25 },
  		["A_C_Horse_Thoroughbred_ReverseDappleBlack"] = { Name = "ReverseDappleBlack", Price = 12.25 },
  	},
  	{
  		name = "Turkoman",
  		["A_C_Horse_Turkoman_DarkBay"]  = { Name = "DarkBay",  Price = 12.25 },
  		["A_C_Horse_Turkoman_Gold"]     = { Name = "Gold",     Price = 12.25 },
  		["A_C_Horse_Turkoman_Silver"]   = { Name = "Silver",   Price = 12.25 },
  		["a_c_horse_turkoman_black"]    = { Name = "black",    Price = 12.25 },
      ["a_c_horse_turkoman_chestnut"] = { Name = "chestnut", Price = 12.25 },
  		["a_c_horse_turkoman_grey"]     = { Name = "grey",     Price = 12.25 },
      ["a_c_horse_turkoman_perlino"]  = { Name = "perlino",  Price = 12.25 },
  	},
  	{
  		name = "Criollo",
  		["A_C_Horse_Criollo_Dun"]           = { Name = "Dun",           Price = 12.25 },
  		["A_C_Horse_Criollo_MarbleSabino"]  = { Name = "MarbleSabino",  Price = 12.25 },
  		["A_C_Horse_Criollo_BayFrameOvero"] = { Name = "BayFrameOvero", Price = 12.25 },
  		["A_C_Horse_Criollo_BayBrindle"]    = { Name = "BayBrindle",    Price = 12.25 },
  		["A_C_Horse_Criollo_SorrelOvero"]   = { Name = "SorrelOvero",   Price = 12.25 },
  		["A_C_Horse_Criollo_BlueRoanOvero"] = { Name = "BlueRoanOvero", Price = 12.25 },
  	},
  	{
  		name = "Breton",
  		["A_C_Horse_Breton_SteelGrey"]   = { Name = "SteelGrey",   Price = 12.25 },
  		["A_C_Horse_Breton_MealyDapple"] = { Name = "MealyDapple", Price = 12.25 },
  		["A_C_Horse_Breton_SealBrown"]   = { Name = "SealBrown",   Price = 12.25 },
  		["A_C_Horse_Breton_GrulloDun"]   = { Name = "GrulloDun",   Price = 12.25 },
  		["A_C_Horse_Breton_Sorrel"]      = { Name = "Sorrel",      Price = 12.25 },
  		["A_C_Horse_Breton_RedRoan"]     = { Name = "RedRoan",     Price = 12.25 },
  	},
  	{
  		name = "Norfolk Roadster",
  		["A_C_HORSE_NORFOLKROADSTER_BLACK"]           = { Name = "BLACK",           Price = 12.25 },
  		["A_C_HORSE_NORFOLKROADSTER_SPECKLEDGREY"]    = { Name = "SPECKLEDGREY",    Price = 12.25 },
  		["A_C_HORSE_NORFOLKROADSTER_PIEBALDROAN"]     = { Name = "PIEBALDROAN",     Price = 12.25 },
  		["A_C_HORSE_NORFOLKROADSTER_ROSEGREY"]        = { Name = "ROSEGREY",        Price = 12.25 },
  		["A_C_HORSE_NORFOLKROADSTER_DAPPLEDBUCKSKIN"] = { Name = "DAPPLEDBUCKSKIN", Price = 12.25 },
  		["A_C_HORSE_NORFOLKROADSTER_SPOTTEDTRICOLOR"] = { Name = "SPOTTEDTRICOLOR", Price = 12.25 },
  	},
  	{
  		name = "Misc",
  		["A_C_HorseMulePainted_01"] = { Name = "Zebra",  Price = 12.25 },
  		["A_C_HorseMule_01"]        = { Name = "Mule",   Price = 12.25 },
  		["A_C_Donkey_01"]           = { Name = "Donkey", Price = 12.25 },
  	},
  }
}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
