Lang['de'] = {
  ["FPS1"] = "Spieler mit PED Nr",
  ["FPS2"] = " ist erschienen^0",
  ["HudDisabled"] = "Die Aktivierung des Hud auf diesem Server wurde deaktiviert",
  ["YourBlacklisted"] = "Du bist auf diesem Server auf der Blacklist! Besuche unseren Discord für weitere Informationen: ",
  ["Blacklist_Main"] = "Blacklist",
  ["AlreadyBlacklist"] = " ist bereits auf der Blacklist",
  ["BlacklistAdded"] = " ist jetzt auf der Blacklist",
  ["BlacklistRemoved"] = "Benutzer mit IP entfernt:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Du wurdest wegen längerer Inaktivität gekickt",
  ["AntiAFKSeconds"] = " ~color_yellow~seconds",
  ["AntiAFKWarning"] = "~color_red~[AFK WARNING]: ~color_yellow~Du wirst gekickt in: ~color_red~",
  ["OnlyForAdmins"] = "Dieser Befehl ist nur für Admins verfügbar!",
  ["SetCharNameNameTo"] = "Name ändern in",
  ["BlacklistCheck"] = "Überprüfen der Server-Blacklist",

  -- Fehler
  ["Error_BlacklistID"] = "Welche Benutzer-ID soll auf die Blacklist gesetzt werden?",
  ["Error_BlacklistType"] = "Benutzer hinzufügen oder entfernen?",
  ["Error_BlackListIP"] = "Der eingegebene Wert ist keine gültige IP-Adresse!",
  ["Error_BlackListName"] = "Welche Benutzer-ID soll auf die Blacklist gesetzt werden?",
  ["Error_BlacklistNotOnList"] = "Benutzer ist nicht auf der Blacklist!",
  ["Error_AddGoldID"] = "Geben Sie die ID des Benutzers ein, dem Sie Gold geben möchten.",
  ["Error_AddGoldType"] = "Muss das in eine Brieftasche oder das Bankkonto gehen?",
  ["Error_AddMoneyID"] = "Geben Sie die ID des Benutzers ein, dem Sie Geld geben möchten.",
  ["Error_AddMoneyType"] = "Muss das in eine Brieftasche oder das Bankkonto gehen?",
  ["Error_AddGoldAmount"] = "Wie viel Gold möchten Sie hinzufügen?",
  ["Error_AddMoneyAmount"] = "Wie viel Geld möchten Sie hinzufügen?",
  ["Error_FirstName"] = "Sie haben keinen Vornamen eingegeben!",
  ["Error_LastName"] = "Sie haben keinen Nachnamen eingegeben!",

  -- Verwendungen
  ["Usage_Blacklist"] = "/blacklist HINZUFÜGEN | ENTFERNEN",
  ["Usage_BlacklistAdd"] = "/blacklist ADD ID [Minuten] [Grund] ",
  ["Usage_BlacklistRemove"] = "/blacklist REMOVE IP",
  ["Usage_AddGold"] = "/addgold ID [ Wallet | Bank ] Betrag",
  ["Usage_AddMoney"] = "/addgold ID [ Wallet | Bank ] Betrag",

  ["CMD:Help:SetCharName"] = "^3Setze deinen Charakternamen^0",
  ["CMD:Help:Discord"] = "^3 Holen Sie sich den Discord-Einladungslink von diesem Server",
  ["CMD:Help:InfoChar"] = "^3 Zeigen Sie Ihre Charakterinformationen auf dem Bildschirm an",
  ["CMD:Help:Help"] = "^3 Zeigen Sie das F8-Hilfe-/Befehlsmenü an",
  ["CMD:Help:SetCharName"] = "^3 Setze deinen Charakternamen^0",
  ["CMD:Help:AddCurrency"] = "^4 CMD ^3| ^4ID ^3| ^4Wallet ^3oder ^4Bank ^3| ^4Amount^0",
  ["CMD:Help:InfoAcc"] = "^3 Zeigen Sie Ihre Kontoinformationen auf dem Bildschirm an",
  ["CMD:Help:Language"] = "^3 Stellen Sie Ihre eigene Client-Sprache ein [ ^4CMD ^3| ^4ID ^3]",
  ["CMD:Help:Coords"] = "^3 Zeigen Sie Ihre aktuellen Koordinaten neben der Minikarte",

  ["MultiChar:IncorrectData"] = "Zeichendaten falsch: Sie haben nicht alle Werte korrekt eingegeben, bitte löschen Sie dieses Zeichen und erstellen Sie ein neues!",

  ['StageCouchAlreadyExists'] = "FEHLER: Sie haben bereits eine StageCouch! Warten Sie, bis sie ihre Route beendet hat!",
  ['StageCouchTitle'] = 'BühnenCouch',
  ['StageCouchOnItsWay'] = 'Auf dem Weg zu Ihrem Standort',
  ['StageCoachArrived'] = "Ihre Fahrt ist angekommen!",
  ['StageCoachArrivedEnd'] = "Sie haben Ihr Ziel erreicht",
}
