Lang['dk'] = {
  ["FPS1"] = "Spiller med PED Nr",
  ["FPS2"] = "har skabt ^ 0",
  ["HudDisabled"] = "Aktivering af Hud på denne server er blevet deaktiveret",
  ["YourBlacklisted"] = "Du er sortlistet på denne server! Besøg vores Discord for mere information:",
  ["Blacklist_Main"] = "Sortliste",
  ["AlreadyBlacklist"] = "er allerede på sortlisten",
  ["BlacklistAdded"] = "er nu på sortlisten",
  ["BlacklistRemoved"] = "Bruger fjernet med IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Du er blevet sparket på grund af langvarig inaktivitet",
  ["AntiAFKSeconds"] = "~ farve_ gule ~ sekunder",
  ["AntiAFKWarning"] = "~ farve_ rød ~ [AFK ADVARSEL]: ~ farve_ gul ~ Du bliver sparket inden for: ~ farve_ rød ~",
  ["OnlyForAdmins"] = "Denne kommando er kun tilgængelig for administratorer!",
  ["SetCharNameNameTo"] = "Navneændring til",
  ["BlacklistCheck"] = "Kontrol af serverens sortliste",

  -- Fejl
  ["Error_BlacklistID"] = "Hvilket bruger-id skal du placere på den sorte liste?",
  ["Error_BlacklistType"] = "Tilføjelse eller fjernelse af brugeren?",
  ["Error_BlackListIP"] = "Den indtastede værdi er ikke en gyldig IP-adresse!",
  ["Error_BlackListName"] = "Hvilket bruger-id skal sættes på sortlisten?",
  ["Error_BlacklistNotOnList"] = "Brugeren er ikke på den sorte liste!",
  ["Error_AddGoldID"] = "Indtast id'et for den bruger, du gerne vil give guld til.",
  ["Error_AddGoldType"] = "Skal dette gå til en tegnebog eller bankkontoen?",
  ["Error_AddMoneyID"] = "Indtast id'et for den bruger, du gerne vil give penge til.",
  ["Error_AddMoneyType"] = "Skal dette gå til en tegnebog eller bankkonto?",
  ["Error_AddGoldAmount"] = "Hvor meget guld vil du tilføje?",
  ["Error_AddMoneyAmount"] = "Hvor mange penge vil du tilføje?",
  ["Error_FirstName"] = "Du indtastede ikke et fornavn!",
  ["Error_LastName"] = "Du indtastede ikke et efternavn!",

  -- Anvendelser
  ["Usage_Blacklist"] = "/ sortliste TILFØJ | FJERN",
  ["Usage_BlacklistAdd"] = "/ sortliste TILFØJ ID [minutter] [Årsag]",
  ["Usage_BlacklistRemove"] = "/ sortliste FJERN IP",
  ["Usage_AddGold"] = "/ addgold ID [tegnebog | bank] beløb",
  ["Usage_AddMoney"] = "/ addgold ID [tegnebog | bank] beløb",

  ["CMD:Help:SetCharName"] = "^ 3Sæt navnet på dine tegn ^ 0",
  ["CMD:Help:Discord"] = "^ 3 Få linket til Discord-invitation fra denne server",
  ["CMD:Help:InfoChar"] = "^ 3 Vis dine karakteroplysninger på skærmen",
  ["CMD:Help:Help"] = "^ 3 Vis menuen F8 Help / Command",
  ["CMD:Help:SetCharName"] = "^ 3 Indstil navnet på dine tegn ^ 0",
  ["CMD:Help:AddCurrency"] = "^ 4 CMD ^ 3 | ^ 4ID ^ 3 | ^ 4Wallet ^ 3eller ^ 4Bank ^ 3 | ^ 4Amount ^ 0",
  ["CMD:Help:InfoAcc"] = "^ 3 Vis dine kontooplysninger på skærmen",
  ["CMD:Help:Language"] = "^ 3 Indstil dit eget klientsprog [^ 4CMD ^ 3 | ^ 4ID ^ 3]",
  ["CMD:Help:Coords"] = "^ 3 Vis dine aktuelle koordinater ud for minimapunktet",

  ["MultiChar:IncorrectData"] = "Tegndata forkert: Du har ikke udfyldt alle værdier korrekt. Slet dette tegn, og opret et nyt!",

  ['StageCouchAlreadyExists'] = "FEJL: Du har allerede en StageCouch! Vent på, at den er færdig med ruten!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'På vej til din placering',
  ['StageCoachArrived'] = "Din tur er ankommet!",
  ['StageCoachArrivedEnd'] = "Du er ankommet til din destination",
}
