Lang['es'] = {
  ["FPS1"] = "Jugador con número de PED",
  ["FPS2"] = "ha generado ^ 0",
  ["HudDisabled"] = "Se ha desactivado la activación de Hud en este servidor",
  ["YourBlacklisted"] = "¡Estás en la lista negra de este servidor! Visita nuestro Discord para obtener más información:",
  ["Blacklist_Main"] = "Lista negra",
  ["AlreadyBlacklist"] = "ya está en la lista negra",
  ["BlacklistAdded"] = "ahora está en la lista negra",
  ["BlacklistRemoved"] = "Usuario eliminado con IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Le han echado debido a inactividad prolongada",
  ["AntiAFKSeconds"] = "~ color_yellow ~ segundos",
  ["AntiAFKWarning"] = "~ color_red ~ [AFK WARNING]: ~ color_yellow ~ Serás expulsado dentro de: ~ color_red ~",
  ["OnlyForAdmins"] = "¡Este comando solo está disponible para administradores!",
  ["SetCharNameNameTo"] = "Cambio de nombre a",
  ["BlacklistCheck"] = "Comprobando la lista negra del servidor",

  -- Errores
  ["Error_BlacklistID"] = "¿Qué ID de usuario poner en la lista negra?",
  ["Error_BlacklistType"] = "¿Agregar o eliminar el usuario?",
  ["Error_BlackListIP"] = "¡El valor ingresado no es una dirección IP válida!",
  ["Error_BlackListName"] = "¿Qué ID de usuario poner en la lista negra?",
  ["Error_BlacklistNotOnList"] = "¡El usuario no está en la lista negra!",
  ["Error_AddGoldID"] = "Ingrese el ID del usuario al que le gustaría regalar oro.",
  ["Error_AddGoldType"] = "¿Esto debe ir a una billetera o cuenta bancaria?",
  ["Error_AddMoneyID"] = "Ingrese el ID del usuario al que le gustaría donar dinero",
  ["Error_AddMoneyType"] = "¿Esto debe ir a una billetera o cuenta bancaria?",
  ["Error_AddGoldAmount"] = "¿Cuánto oro desea agregar?",
  ["Error_AddMoneyAmount"] = "¿Cuánto dinero desea agregar?",
  ["Error_FirstName"] = "¡No ingresaste un nombre!",
  ["Error_LastName"] = "¡No ingresaste un apellido!",

  -- Usos
  ["Usage_Blacklist"] = "/ lista negra AÑADIR | ELIMINAR",
  ["Usage_BlacklistAdd"] = "/ lista negra ADD ID [Minutos] [Reason]",
  ["Usage_BlacklistRemove"] = "/ lista negra ELIMINAR IP",
  ["Usage_AddGold"] = "/ monto de ID de addgold [billetera | banco]",
  ["Usage_AddMoney"] = "/ monto de ID de addgold [billetera | banco]",

  ["CMD:Help:SetCharName"] = "^ 3Configure el nombre de su personaje ^ 0",
  ["CMD:Help:Discord"] = "^ 3 Obtén el enlace de invitación de Discord desde este servidor",
  ["CMD:Help:InfoChar"] = "^ 3 Muestra la información de tu personaje en la pantalla",
  ["CMD:Help:Help"] = "^ 3 Mostrar el menú Ayuda / Comando de F8",
  ["CMD:Help:SetCharName"] = "^ 3 Establece el nombre de tu personaje ^ 0",
  ["CMD:Help:AddCurrency"] = "^ 4 CMD ^ 3 | ^ 4ID ^ 3 | ^ 4Wallet ^ 3or ^ 4Bank ^ 3 | ^ 4Amount ^ 0",
  ["CMD:Help:InfoAcc"] = "^ 3 Muestra la información de su cuenta en la pantalla",
  ["CMD:Help:Language"] = "^ 3 Configure su propio idioma de cliente [^ 4CMD ^ 3 | ^ 4ID ^ 3]",
  ["CMD:Help:Coords"] = "^ 3 Muestra tus coordenadas actuales junto al minimapa",

  ["MultiChar:IncorrectData"] = "Datos de caracteres incorrectos: No ha completado todos los valores correctamente, elimine este carácter y cree uno nuevo",

  ['StageCouchAlreadyExists'] = "ERROR: ¡Ya tiene un StageCouch! ¡Espere a que termine su ruta!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'De camino a su ubicación',
  ['StageCoachArrived'] = "¡Tu viaje ha llegado!",
  ['StageCoachArrivedEnd'] = "Ha llegado a su destino",
}
