Lang['fr'] = {
  ["FPS1"] = "Lecteur avec PED Nr ",
  ["FPS2"] = " a généré^0",
  ["HudDisabled"] = "L'activation du Hud sur ce serveur a été désactivée",
  ["YourBlacklisted"] = "Vous êtes Blacklisted sur ce serveur ! Visitez notre Discord pour plus d'informations : ",
  ["Blacklist_Main"] = "Blacklist",
  ["AlreadyBlacklist"] = " est déjà sur la liste noire",
  ["BlacklistAdded"] = " est maintenant sur la liste noire",
  ["BlacklistRemoved"] = "Utilisateur supprimé avec IP :",
  ["AntiAFKKickPlayer"] = "[AntiAFK] : vous avez été expulsé en raison d'une inactivité prolongée",
  ["AntiAFKSeconds"] = " ~color_yellow~secondes",
  ["AntiAFKWarning"] = "~color_red~[AFK WARNING] : ~color_yellow~Vous serez expulsé dans : ~color_red~",
  ["OnlyForAdmins"] = "Cette commande n'est disponible que pour les administrateurs !",
  ["SetCharNameNameTo"] = "Nom changé en",
  ["BlacklistCheck"] = "Vérification de la liste noire du serveur",

  ["Error_BlacklistID"] = "Quel identifiant d'utilisateur mettre sur la liste noire ?",
  ["Error_BlacklistType"] = "Ajouter ou supprimer l'utilisateur ?",
  ["Error_BlackListIP"] = "La valeur saisie n'est pas une adresse IP valide !",
  ["Error_BlackListName"] = "Quel ID utilisateur mettre sur la liste noire ?",
  ["Error_BlacklistNotOnList"] = "L'utilisateur n'est pas sur la liste noire !",
  ["Error_AddGoldID"] = "Entrez l'ID de l'utilisateur auquel vous souhaitez donner de l'or.",
  ["Error_AddGoldType"] = "Est-ce que cela doit aller dans un portefeuille ou sur le compte bancaire ?",
  ["Error_AddMoneyID"] = "Entrez l'ID de l'utilisateur auquel vous souhaitez donner de l'argent.",
  ["Error_AddMoneyType"] = "Est-ce que cela doit aller dans un portefeuille ou sur le compte bancaire ?",
  ["Error_AddGoldAmount"] = "Combien d'or voulez-vous ajouter ?",
  ["Error_AddMoneyAmount"] = "Combien d'argent voulez-vous ajouter ?",
  ["Error_FirstName"] = "Vous n'avez pas saisi de prénom !",
  ["Error_LastName"] = "Vous n'avez pas saisi de nom de famille !",

  ["Usage_Blacklist"] = "/blacklist AJOUTER | SUPPRIMER",
  ["Usage_BlacklistAdd"] = "/blacklist ADD ID [Minutes] [Raison] ",
  ["Usage_BlacklistRemove"] = "/blacklist SUPPRIMER IP",
  ["Usage_AddGold"] = "/addgold ID [portefeuille | banque] montant",
  ["Usage_AddMoney"] = "/addgold ID [portefeuille | banque] montant",

  ["CMD:Help:SetCharName"] = "^3Définissez le nom de vos caractères^0",
  ["CMD:Help:Discord"] = "^3 Obtenez le lien d'invitation Discord de ce serveur",
  ["CMD:Help:InfoChar"] = "^3 Affichez les informations de votre personnage à l'écran",
  ["CMD:Help:Help"] = "^3 Affiche le menu Aide / Commande F8",
  ["CMD:Help:SetCharName"] = "^3 Définissez le nom de vos caractères^0",
  ["CMD:Help:AddCurrency"] = "^4 CMD ^3| ^4ID ^3| ^4Wallet ^3ou ^4Bank ^3| ^4Amount^0",
  ["CMD:Help:InfoAcc"] = "^3 Affichez les informations de votre compte à l'écran",
  ["CMD:Help:Language"] = "^3 Définissez votre propre langue client [ ^4CMD ^3| ^4ID ^3]",
  ["CMD:Help:Coords"] = "^3 Affichez vos coordonnées actuelles à côté de la minicarte",
  ['CMD_Help_Hud'] = '^3 Mettre à jour, afficher ou masquer le Hud^0',

  ["MultiChar:IncorrectData"] = "Données de caractère incorrectes : vous n'avez pas rempli toutes les valeurs correctement, veuillez supprimer ce caractère et en créer un nouveau !",

  ['StageCouchAlreadyExists'] = "ERREUR : vous avez déjà un StageCouch ! Attendez qu'il termine son parcours !",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'En route vers votre position',
  ['StageCoachArrived'] = "Votre course est arrivée !",
  ['StageCoachArrivedEnd'] = "Vous êtes arrivé à destination",

}
