Lang['gr'] = {
  ["FPS1"] = "Παίκτης με PED Nr",
  ["FPS2"] = "έχει δημιουργηθεί ^ 0",
  ["HudDisabled"] = "Η ενεργοποίηση του Hud σε αυτόν τον διακομιστή έχει απενεργοποιηθεί",
  ["YourBlacklisted"] = "Είστε μαύρη λίστα σε αυτόν τον διακομιστή! Επισκεφτείτε τη Συμφωνία για περισσότερες πληροφορίες:",
  ["Blacklist_Main"] = "Μαύρη λίστα",
  ["AlreadyBlacklist"] = "βρίσκεται ήδη στη μαύρη λίστα",
  ["BlacklistAdded"] = "είναι πλέον στη Μαύρη λίστα",
  ["BlacklistRemoved"] = "Ο χρήστης καταργήθηκε με IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Έχετε κλωτσήσει λόγω παρατεταμένης αδράνειας",
  ["AntiAFKSeconds"] = "~ color_yellow ~ seconds",
  ["AntiAFKWarning"] = "~ color_red ~ [AFK ΠΡΟΕΙΔΟΠΟΙΗΣΗ]: ~ color_yellow ~ Θα σας κλωτσήσει εντός: ~ color_red ~",
  ["OnlyForAdmins"] = "Αυτή η εντολή είναι διαθέσιμη μόνο για διαχειριστές!",
  ["SetCharNameNameTo"] = "Αλλαγή ονόματος σε",
  ["BlacklistCheck"] = "Έλεγχος της μαύρης λίστας διακομιστή",

  ["Error_BlacklistID"] = "Ποιο αναγνωριστικό χρήστη θα τοποθετηθεί στη μαύρη λίστα;",
  ["Error_BlacklistType"] = "Προσθήκη ή κατάργηση του χρήστη;",
  ["Error_BlackListIP"] = "Η τιμή που εισαγάγατε δεν είναι έγκυρη διεύθυνση IP!",
  ["Error_BlackListName"] = "Ποιο αναγνωριστικό χρήστη θα τοποθετηθεί στη μαύρη λίστα;",
  ["Error_BlacklistNotOnList"] = "Ο χρήστης δεν είναι στη μαύρη λίστα!",
  ["Error_AddGoldID"] = "Εισαγάγετε το αναγνωριστικό του χρήστη στον οποίο θέλετε να δώσετε χρυσό.",
  ["Error_AddGoldType"] = "Χρειάζεται να πάει σε πορτοφόλι ή στον τραπεζικό λογαριασμό;",
  ["Error_AddMoneyID"] = "Εισαγάγετε το αναγνωριστικό του χρήστη στον οποίο θέλετε να δώσετε χρήματα.",
  ["Error_AddMoneyType"] = "Πρέπει να μεταβείτε σε ένα πορτοφόλι ή στον τραπεζικό λογαριασμό;",
  ["Error_AddGoldAmount"] = "Πόσο χρυσό θέλετε να προσθέσετε;",
  ["Error_AddMoneyAmount"] = "Πόσα χρήματα θέλετε να προσθέσετε;",
  ["Error_FirstName"] = "Δεν εισαγάγατε ένα όνομα!",
  ["Error_LastName"] = "Δεν εισαγάγατε επώνυμο!",

  ["Usage_Blacklist"] = "/ μαύρη λίστα ΠΡΟΣΘΗΚΗ | ΚΑΤΑΡΓΗΣΗ",
  ["Usage_BlacklistAdd"] = "/ blacklist ADD ID [Minutes] [Reason]",
  ["Usage_BlacklistRemove"] = "/ μαύρη λίστα ΑΦΑΙΡΕΣΗ IP",
  ["Usage_AddGold"] = "/ addgold ID [wallet | bank] ποσό",
  ["Usage_AddMoney"] = "/ addgold ID [wallet | bank] ποσό",

  ["CMD:Help:SetCharName"] = "^ 3Ρυθμίστε το όνομα των χαρακτήρων σας ^ 0",
  ["CMD:Help:Discord"] = "^ 3 Λήψη του συνδέσμου πρόσκλησης Discord από αυτόν τον διακομιστή",
  ["CMD:Help:InfoChar"] = "^ 3 Εμφάνιση των πληροφοριών χαρακτήρων στην οθόνη",
  ["CMD:Help:Help"] = "^ 3 Εμφάνιση του μενού F8 Help / Command",
  ["CMD:Help:SetCharName"] = "^ 3 Ορίστε το όνομα των χαρακτήρων σας ^ 0",
  ["CMD:Help:AddCurrency"] = "^ 4 CMD ^ 3 | ^ 4ID ^ 3 | ^ 4Wallet ^ 3or ^ 4Bank ^ 3 | ^ 4Amount ^ 0",
  ["CMD:Help:InfoAcc"] = "^ 3 Εμφάνιση των πληροφοριών του λογαριασμού σας στην οθόνη",
  ["CMD:Help:Language"] = "^ 3 Ορίστε τη δική σας γλώσσα πελάτη [^ 4CMD ^ 3 | ^ 4ID ^ 3]",
  ["CMD:Help:Coords"] = "^ 3 Δείξτε τις τρέχουσες συντεταγμένες σας δίπλα στο minimap",
  ['CMD_Help_Hud'] = '^3 Ενημέρωση, εμφάνιση ή απόκρυψη του Hud^0',

  ["MultiChar:IncorrectData"] = "Λάθος δεδομένα χαρακτήρων: Δεν έχετε συμπληρώσει σωστά όλες τις τιμές, διαγράψτε αυτόν τον χαρακτήρα και δημιουργήστε έναν νέο!",

  ['StageCouchAlreadyExists'] = "ΛΑΘΟΣ: Έχετε ήδη ένα StageCouch! Περιμένετε να τελειώσει η διαδρομή του!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'Στο δρόμο για την τοποθεσία σας',
  ['StageCoachArrived'] = "Η βόλτα σας έφτασε!",
  ['StageCoachArrivedEnd'] = "Φτάσατε στον προορισμό σας",

}
