Lang['it'] = {
  ["FPS1"] = "Giocatore con PED Nr ",
  ["FPS2"] = "è generato^0",
  ["HudDisabled"] = "L'attivazione dell'Hud su questo server è stata disabilitata",
  ["YourBlacklisted"] = "Sei nella lista nera su questo server! Visita il nostro Discord per ulteriori informazioni: ",
  ["Blacklist_Main"] = "Lista nera",
  ["AlreadyBlacklist"] = "è già nella Blacklist",
  ["BlacklistAdded"] = "è ora nella lista nera",
  ["BlacklistRemoved"] = "Utente rimosso con IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Sei stato espulso per inattività prolungata",
  ["AntiAFKSeconds"] = " ~colore_giallo~secondi",
  ["AntiAFKWarning"] = "~color_red~[AFK WARNING]: ~color_yellow~Verrai espulso entro: ~color_red~",
  ["OnlyForAdmins"] = "Questo comando è disponibile solo per gli amministratori!",
  ["SetCharNameNameTo"] = "Nome cambia in",
  ["BlacklistCheck"] = "Controllo della lista nera del server",

  ["Error_BlacklistID"] = "Quale ID utente inserire nella Blacklist?",
  ["Error_BlacklistType"] = "Aggiungi o rimuovi l'utente?",
  ["Error_BlackListIP"] = "Il valore inserito non è un indirizzo IP valido!",
  ["Error_BlackListName"] = "Quale ID utente inserire nella Blacklist?",
  ["Error_BlacklistNotOnList"] = "L'utente non è nella lista nera!",
  ["Error_AddGoldID"] = "Inserisci l'ID dell'utente a cui vuoi regalare l'oro.",
  ["Error_AddGoldType"] = "Deve andare su un portafoglio o sul conto bancario?",
  ["Error_AddMoneyID"] = "Inserisci l'ID dell'utente a cui desideri donare denaro.",
  ["Error_AddMoneyType"] = "Deve andare su un portafoglio o sul conto bancario?",
  ["Error_AddGoldAmount"] = "Quanto oro vuoi aggiungere?",
  ["Error_AddMoneyAmount"] = "Quanti soldi vuoi aggiungere?",
  ["Error_FirstName"] = "Non hai inserito un nome!",
  ["Error_LastName"] = "Non hai inserito un cognome!",

  ["Usage_Blacklist"] = "/blacklist AGGIUNGI | RIMUOVI",
  ["Usage_BlacklistAdd"] = "/blacklist AGGIUNGI ID [Minuti] [Motivo] ",
  ["Usage_BlacklistRemove"] = "/blacklist RIMUOVI IP",
  ["Usage_AddGold"] = "/addgold ID [portafoglio | banca] importo",
  ["Usage_AddMoney"] = "/addgold ID [portafoglio | banca] importo",

  ["CMD:Help:SetCharName"] = "^3Imposta il nome del tuo personaggio^0",
  ["CMD:Help:Discord"] = "^3 Ottieni il link di invito Discord da questo server",
  ["CMD:Help:InfoChar"] = "^3 Visualizza le informazioni del tuo personaggio sullo schermo",
  ["CMD:Help:Help"] = "^3 Visualizza il menu Aiuto/Comando F8",
  ["CMD:Help:SetCharName"] = "^3 Imposta il nome del tuo personaggio^0",
  ["CMD:Help:AddCurrency"] = "^4 CMD ^3| ^4ID ^3| ^4Portafoglio ^3o ^4Banca ^3| ^4Importo^0",
  ["CMD:Help:InfoAcc"] = "^3 Visualizza le informazioni del tuo account sullo schermo",
  ["CMD:Help:Language"] = "^3 Imposta la tua lingua client [ ^4CMD ^3| ^4ID ^3]",
  ["CMD:Help:Coords"] = "^3 Mostra le tue coordinate attuali accanto alla minimappa",
  ['CMD_Help_Hud'] = "^3 Aggiorna, mostra o nascondi l'Hud^0",

  ["MultiChar:IncorrectData"] = "Dati carattere errati: non hai inserito tutti i valori correttamente, elimina questo carattere e creane uno nuovo!",

  ['StageCouchAlreadyExists'] = "ERRORE: hai già uno StageCouch! Attendi che finisca il suo percorso!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'In viaggio verso la tua posizione',
  ['StageCoachArrived'] = "La tua corsa è arrivata!",
  ['StageCoachArrivedEnd'] = "Sei arrivato a destinazione",

}
