Lang['nl'] = {
  ["FPS1"] = "Speler met PED Nr ",
  ["FPS2"] = " heeft voortgebracht^0",
  ["HudDisabled"] = "Het activeren van de Hud op deze server is uitgeschakeld",
  ["YourBlacklisted"] = "Je staat op de zwarte lijst op deze server! Bezoek onze Discord voor meer informatie: ",
  ["Blacklist_Main"] = "Zwarte lijst",
  ["AlreadyBlacklist"] = " staat al op de zwarte lijst",
  ["BlacklistAdded"] = " staat nu op de zwarte lijst",
  ["BlacklistRemoved"] = "Gebruiker verwijderd met IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Je bent geschopt vanwege langdurige inactiviteit",
  ["AntiAFKSeconds"] = " ~color_yellow~seconds",
  ["AntiAFKWarning"] = "~color_red~[AFK WARNING]: ~color_yellow~Je wordt binnen getrapt: ~color_red~",
  ["OnlyForAdmins"] = "Deze opdracht is alleen beschikbaar voor beheerders!",
  ["SetCharNameNameTo"] = "Naam wijzigen in",
  ["BlacklistCheck"] = "De zwarte lijst van de server controleren",

  ["Error_BlacklistID"] = "Welke gebruikers-ID moet op de zwarte lijst worden gezet?",
  ["Error_BlacklistType"] = "Gebruiker toevoegen of verwijderen?",
  ["Error_BlackListIP"] = "De ingevoerde waarde is geen geldig IP-adres!",
  ["Error_BlackListName"] = "Welke gebruikers-ID moet op de zwarte lijst worden gezet?",
  ["Error_BlacklistNotOnList"] = "Gebruiker staat niet op de zwarte lijst!",
  ["Error_AddGoldID"] = "Voer de ID in van de gebruiker aan wie u goud wilt geven.",
  ["Error_AddGoldType"] = "Moet dit naar een portemonnee of bankrekening gaan?",
  ["Error_AddMoneyID"] = "Voer de ID in van de gebruiker aan wie u geld wilt geven.",
  ["Error_AddMoneyType"] = "Moet dit naar een portemonnee of bankrekening gaan?",
  ["Error_AddGoldAmount"] = "Hoeveel goud wilt u toevoegen?",
  ["Error_AddMoneyAmount"] = "Hoeveel geld wilt u toevoegen?",
  ["Error_FirstName"] = "Je hebt geen voornaam ingevoerd!",
  ["Error_LastName"] = "Je hebt geen achternaam ingevoerd!",

  ["Usage_Blacklist"] = "/blacklist TOEVOEGEN | VERWIJDEREN",
  ["Usage_BlacklistAdd"] = "/blacklist ADD ID [Minuten] [Reden] ",
  ["Usage_BlacklistRemove"] = "/blacklist REMOVE IP",
  ["Usage_AddGold"] = "/addgold ID [ portemonnee | bank ] bedrag",
  ["Usage_AddMoney"] = "/addgold ID [ portemonnee | bank ] bedrag",

  ["CMD:Help:SetCharName"] = "^3Stel de naam van je karakter in^0",
  ["CMD:Help:Discord"] = "^3 Haal de Discord-uitnodigingslink van deze server",
  ["CMD:Help:InfoChar"] = "^3 Toon uw karakterinformatie op het scherm",
  ["CMD:Help:Help"] = "^3 Geef het F8 Help / Command-menu weer",
  ["CMD:Help:SetCharName"] = "^3 Stel de naam van je karakter in^0",
  ["CMD:Help:AddCurrency"] = "^4 CMD ^3| ^4ID ^3| ^4Wallet ^3of ^4Bank ^3| ^4Bedrag^0",
  ["CMD:Help:InfoAcc"] = "^3 Toon uw accountinformatie op het scherm",
  ["CMD:Help:Language"] = "^3 Stel uw eigen klanttaal in [ ^4CMD ^3| ^4ID ^3]",
  ["CMD:Help:Coords"] = "^3 Toon uw huidige coördinaten naast de minikaart",

  ["MultiChar:IncorrectData"] = "Tekengegevens onjuist: u heeft niet alle waarden correct ingevuld, verwijder dit teken en maak een nieuwe aan!",

  ['StageCouchAlreadyExists'] = "FOUT: U heeft al een StageCouch! Wacht tot deze zijn route heeft voltooid!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'Op weg naar uw locatie',
  ['StageCoachArrived'] = "Uw rit is gearriveerd!",
  ['StageCoachArrivedEnd'] = "U bent op uw bestemming aangekomen",
}
