Lang['pl'] = {
  ["FPS1"] = "Gracz z PED Nr",
  ["FPS2"] = " odrodził^0",
  ["HudDisabled"] = "Aktywacja Huda na tym serwerze została wyłączona",
  ["YourBlacklisted"] = "Jesteś na czarnej liście na tym serwerze! Odwiedź nasz Discord, aby uzyskać więcej informacji: ",
  ["Blacklist_Main"] = "Czarna lista",
  ["AlreadyBlacklist"] = " jest już na czarnej liście",
  ["BlacklistAdded"] = " jest teraz na czarnej liście",
  ["BlacklistRemoved"] = "Użytkownik usunięty z IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Zostałeś wyrzucony z powodu dłuższej bezczynności",
  ["AntiAFKSeconds"] = " ~kolor_żółty~sekundy",
  ["AntiAFKWarning"] = "~kolor_czerwony~[OSTRZEŻENIE AFK]: ~kolor_żółty~Zostaniesz wyrzucony za: ~kolor_czerwony~",
  ["OnlyForAdmins"] = "To polecenie jest dostępne tylko dla administratorów!",
  ["SetCharNameNameTo"] = "Nazwa Zmień na",
  ["BlacklistCheck"] = "Sprawdzanie czarnej listy serwerów",

  ["Error_BlacklistID"] = "Jaki identyfikator użytkownika umieścić na czarnej liście?",
  ["Error_BlacklistType"] = "Dodawać lub usuwać użytkownika?",
  ["Error_BlackListIP"] = "Wprowadzona wartość nie jest prawidłowym adresem IP!",
  ["Error_BlackListName"] = "Jaki identyfikator użytkownika umieścić na czarnej liście?",
  ["Error_BlacklistNotOnList"] = "Użytkownika nie ma na czarnej liście!",
  ["Error_AddGoldID"] = "Wprowadź identyfikator użytkownika, któremu chcesz dać złoto.",
  ["Error_AddGoldType"] = "Czy to musi iść do portfela czy konta bankowego?",
  ["Error_AddMoneyID"] = "Wprowadź identyfikator użytkownika, któremu chcesz przekazać pieniądze.",
  ["Error_AddMoneyType"] = "Czy to musi trafić do portfela czy konta bankowego?",
  ["Error_AddGoldAmount"] = "Ile złota chcesz dodać?",
  ["Error_AddMoneyAmount"] = "Ile pieniędzy chcesz dodać?",
  ["Error_FirstName"] = "Nie wpisałeś imienia!",
  ["Error_LastName"] = "Nie wpisałeś nazwiska!",

  ["Usage_Blacklist"] = "/blacklist DODAJ | USUŃ",
  ["Usage_BlacklistAdd"] = "/blacklist ADD ID [Minuty] [Powód] ",
  ["Usage_BlacklistRemove"] = "/blacklist USUŃ IP",
  ["Usage_AddGold"] = "/addgold ID [ portfel | bank ] kwota",
  ["Usage_AddMoney"] = "/addgold ID [ portfel | bank ] kwota",

  ["CMD:Help:SetCharName"] = "^3Ustaw nazwę postaci^0",
  ["CMD:Help:Discord"] = "^3 Uzyskaj link z zaproszeniem Discord z tego serwera",
  ["CMD:Help:InfoChar"] = "^3 Wyświetlaj informacje o swojej postaci na ekranie",
  ["CMD:Help:Help"] = "^3 Wyświetl menu Pomoc / Polecenia F8",
  ["CMD:Help:SetCharName"] = "^3 Ustaw nazwę postaci^0",
  ["CMD:Help:AddCurrency"] = "^4 CMD ^3| ^4ID ^3| ^4Wallet ^3lub ^4Bank ^3| ^4Kwota^0",
  ["CMD:Help:InfoAcc"] = "^3 Wyświetl informacje o swoim koncie na ekranie",
  ["CMD:Help:Language"] = "^3 Ustaw własny język klienta [ ^4CMD ^3| ^4ID ^3]",
  ["CMD:Help:Coords"] = "^3 Pokaż swoje aktualne współrzędne obok minimapy",

  ["MultiChar:IncorrectData"] = "Nieprawidłowe dane znaku: Nie podałeś poprawnie wszystkich wartości, usuń ten znak i utwórz nowy!",

  ['StageCouchAlreadyExists'] = "BŁĄD: Masz już StageCouch! Poczekaj, aż zakończy trasę!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'W drodze do Twojej lokalizacji',
  ['StageCoachArrived'] = "Twoja jazda dotarła!",
  ['StageCoachArrivedEnd'] = "Dotarłeś do celu",
}
