Lang['pt'] = {
  ["FPS1"] = "Jogador com PED Nr",
  ["FPS2"] = "gerou ^ 0",
  ["HudDisabled"] = "A ativação do Hud neste servidor foi desabilitada",
  ["YourBlacklisted"] = "Você está na lista negra deste servidor! Visite nosso Discord para obter mais informações:",
  ["Blacklist_Main"] = "Lista negra",
  ["AlreadyBlacklist"] = "já está na lista negra",
  ["BlacklistAdded"] = "agora está na lista negra",
  ["BlacklistRemoved"] = "Usuário removido com IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Você foi expulso devido a inatividade prolongada",
  ["AntiAFKSeconds"] = "~ color_yellow ~ segundos",
  ["AntiAFKWarning"] = "~ color_red ~ [AFK WARNING]: ~ color_yellow ~ Você será chutado em: ~ color_red ~",
  ["OnlyForAdmins"] = "Este comando está disponível apenas para administradores!",
  ["SetCharNameNameTo"] = "Mudança de nome para",
  ["BlacklistCheck"] = "Verificando a lista negra do servidor",

  ["Error_BlacklistID"] = "Qual ID de usuário colocar na lista negra?",
  ["Error_BlacklistType"] = "Adicionando ou removendo o usuário?",
  ["Error_BlackListIP"] = "O valor inserido não é um endereço IP válido!",
  ["Error_BlackListName"] = "Qual ID de usuário colocar na lista negra?",
  ["Error_BlacklistNotOnList"] = "O usuário não está na lista negra!",
  ["Error_AddGoldID"] = "Digite a ID do usuário a quem você gostaria de dar ouro.",
  ["Error_AddGoldType"] = "É necessário ir para uma carteira ou conta bancária?",
  ["Error_AddMoneyID"] = "Digite o ID do usuário para o qual você gostaria de dar dinheiro.",
  ["Error_AddMoneyType"] = "É necessário ir para uma carteira ou conta bancária?",
  ["Error_AddGoldAmount"] = "Quanto ouro você deseja adicionar?",
  ["Error_AddMoneyAmount"] = "Quanto dinheiro você deseja adicionar?",
  ["Error_FirstName"] = "Você não digitou o primeiro nome!",
  ["Error_LastName"] = "Você não digitou um sobrenome!",

  ["Usage_Blacklist"] = "/ lista negra ADICIONAR | REMOVER",
  ["Usage_BlacklistAdd"] = "/ lista negra ADD ID [Minutos] [Razão]",
  ["Usage_BlacklistRemove"] = "/ lista negra REMOVER IP",
  ["Usage_AddGold"] = "/ addgold ID [carteira | banco] montante",
  ["Usage_AddMoney"] = "/ addgold ID [carteira | banco] montante",

  ["CMD:Help:SetCharName"] = "^ 3Defina o nome de seus personagens ^ 0",
  ["CMD:Help:Discord"] = "^ 3 Obtenha o link de convite do Discord neste servidor",
  ["CMD:Help:InfoChar"] = "^ 3 Exibir as informações do seu personagem na tela",
  ["CMD:Help:Help"] = "^ 3 Exibir o menu Ajuda / Comando F8",
  ["CMD:Help:SetCharName"] = "^ 3 Defina o nome de seus personagens ^ 0",
  ["CMD:Help:AddCurrency"] = "^ 4 CMD ^ 3 | ^ 4ID ^ 3 | ^ 4Wallet ^ 3ou ^ 4Bank ^ 3 | ^ 4Amount ^ 0",
  ["CMD:Help:InfoAcc"] = "^ 3 Exibir as informações de sua conta na tela",
  ["CMD:Help:Language"] = "^ 3 Defina seu próprio idioma de cliente [^ 4CMD ^ 3 | ^ 4ID ^ 3]",
  ["CMD:Help:Coords"] = "^ 3 Mostrar suas coordenadas atuais ao lado do minimapa",
  ['CMD_Help_Hud'] = '^ 3 Atualizar, mostrar ou ocultar o Hud ^ 0',

  ["MultiChar:IncorrectData"] = "Dados do caractere incorretos: você não preencheu todos os valores corretamente, exclua este caractere e crie um novo!",

  ['StageCouchAlreadyExists'] = "ERRO: Você já tem um StageCouch! Aguarde até que ele termine sua rota!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'A caminho de sua localização',
  ['StageCoachArrived'] = "Sua viagem chegou!",
  ['StageCoachArrivedEnd'] = "Você chegou ao seu destino",

}
