Lang['ru'] = {
  ["FPS1"] = "Игрок с номером PED",
  ["FPS2"] = "породил ^ 0",
  ["HudDisabled"] = "Активация Hud на этом сервере отключена",
  ["YourBlacklisted"] = "Вы занесены в черный список на этом сервере! Посетите наш Discord для получения дополнительной информации:",
  ["Blacklist_Main"] = "Черный список",
  ["AlreadyBlacklist"] = "уже в черном списке",
  ["BlacklistAdded"] = "теперь в черном списке",
  ["BlacklistRemoved"] = "Пользователь удален с IP:",
  ["AntiAFKKickPlayer"] = "[AntiAFK]: Вас выгнали из-за длительного бездействия",
  ["AntiAFKSeconds"] = "~ цвет_желтый ~ секунд",
  ["AntiAFKWarning"] = "~ color_red ~ [ПРЕДУПРЕЖДЕНИЕ AFK]: ~ color_yellow ~ Вы будете выгнаны через: ~ color_red ~",
  ["OnlyForAdmins"] = "Эта команда доступна только для администраторов!",
  ["SetCharNameNameTo"] = "Изменить имя на",
  ["BlacklistCheck"] = "Проверка черного списка серверов",

  ["Error_BlacklistID"] = "Какой идентификатор пользователя добавить в черный список?",
  ["Error_BlacklistType"] = "Добавление или удаление пользователя?",
  ["Error_BlackListIP"] = "Введенное значение не является действительным IP-адресом!",
  ["Error_BlackListName"] = "Какой идентификатор пользователя добавить в черный список?",
  ["Error_BlacklistNotOnList"] = "Пользователь не находится в черном списке!",
  ["Error_AddGoldID"] = "Введите идентификатор пользователя, которому вы хотите дать золото.",
  ["Error_AddGoldType"] = "Это нужно для перехода к кошельку или банковскому счету?",
  ["Error_AddMoneyID"] = "Введите идентификатор пользователя, которому вы хотите дать деньги.",
  ["Error_AddMoneyType"] = "Это нужно для перехода к кошельку или банковскому счету?",
  ["Error_AddGoldAmount"] = "Сколько золота вы хотите добавить?",
  ["Error_AddMoneyAmount"] = "Сколько денег вы хотите добавить?",
  ["Error_FirstName"] = "Вы не ввели имя!",
  ["Error_LastName"] = "Вы не ввели фамилию!",

  ["Usage_Blacklist"] = "/ черный список ДОБАВИТЬ | УДАЛИТЬ",
  ["Usage_BlacklistAdd"] = "/ черный список ДОБАВИТЬ ID [Минуты] [Причина]",
  ["Usage_BlacklistRemove"] = "/ черный список УДАЛИТЬ IP",
  ["Usage_AddGold"] = "/ addgold ID [кошелек | банк] сумма",
  ["Usage_AddMoney"] = "/ addgold ID [кошелек | банк] сумма",

  ["CMD:Help:SetCharName"] = "^ 3Установите имя персонажа ^ 0",
  ["CMD:Help:Discord"] = "^ 3 Получить ссылку приглашения Discord с этого сервера",
  ["CMD:Help:InfoChar"] = "^ 3 Отобразить информацию о вашем персонаже на экране",
  ["CMD:Help:Help"] = "^ 3 Отобразить меню F8 Help / Command",
  ["CMD:Help:SetCharName"] = "^ 3 Задайте имя персонажа ^ 0",
  ["CMD:Help:AddCurrency"] = "^ 4 CMD ^ 3 | ^ 4ID ^ 3 | ^ 4Wallet ^ 3or ^ 4Bank ^ 3 | ^ 4Amount ^ 0",
  ["CMD:Help:InfoAcc"] = "^ 3 Отобразить информацию о вашей учетной записи на экране",
  ["CMD:Help:Language"] = "^ 3 Установите собственный язык клиента [^ 4CMD ^ 3 | ^ 4ID ^ 3]",
  ["CMD:Help:Coords"] = "^ 3 Показывать ваши текущие координаты рядом с мини-картой",
  ['CMD_Help_Hud'] = '^ 3 Обновить, показать или скрыть Hud ^ 0',

  ["MultiChar:IncorrectData"] = "Неверные данные символа: вы неправильно ввели все значения, удалите этот символ и создайте новый!",

  ['StageCouchAlreadyExists'] = "ОШИБКА: у вас уже есть StageCouch! Подождите, пока он завершит свой маршрут!",
  ['StageCouchTitle'] = 'StageCouch',
  ['StageCouchOnItsWay'] = 'На пути к вам',
  ['StageCoachArrived'] = "Ваша поездка прибыла!",
  ['StageCoachArvedEnd'] = "Вы прибыли в пункт назначения",

}
