-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.11.1-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for dokuscore
CREATE DATABASE IF NOT EXISTS `dokuscore` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `dokuscore`;

-- Drop tables that are altered.
DROP TABLE IF EXISTS `_items`;
DROP TABLE IF EXISTS `_stores`;

-- Dumping structure for table dokuscore._items
CREATE TABLE IF NOT EXISTS `_items` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Item` varchar(50) DEFAULT NULL,
  `Name` varchar(50) DEFAULT NULL,
  `Type` varchar(50) DEFAULT NULL,
  `Description` longtext NOT NULL DEFAULT '--',
  `CTI` varchar(50) DEFAULT NULL,
  `CA` int(11) DEFAULT 0,
  `InvLimit` int(11) DEFAULT 100,
  `CanPlace` tinyint(4) DEFAULT NULL,
  `Delete` tinyint(4) DEFAULT NULL,
  `UseMeta` tinyint(4) DEFAULT NULL,
  `UseEvent` tinyint(4) DEFAULT NULL,
  `UseAnim` tinyint(4) DEFAULT NULL,
  `Hunger` float DEFAULT NULL,
  `Thirst` float DEFAULT NULL,
  `Health` int(11) DEFAULT NULL,
  `Stamina` int(11) DEFAULT NULL,
  `GHI` int(11) DEFAULT NULL,
  `GHO` int(11) DEFAULT NULL,
  `GSI` int(11) DEFAULT NULL,
  `GSO` int(11) DEFAULT NULL,
  `Animation` longtext DEFAULT NULL,
  `Event` varchar(100) DEFAULT NULL,
  `Meta` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table dokuscore._items: ~78 rows (approximately)
/*!40000 ALTER TABLE `_items` DISABLE KEYS */;
INSERT INTO `_items` (`ID`, `Item`, `Name`, `Type`, `Description`, `CTI`, `CA`, `InvLimit`, `CanPlace`, `Delete`, `UseMeta`, `UseEvent`, `UseAnim`, `Hunger`, `Thirst`, `Health`, `Stamina`, `GHI`, `GHO`, `GSI`, `GSO`, `Animation`, `Event`, `Meta`) VALUES
	(1, 'carrot', 'Carrot', 'Consumable', 'Its orange! Its healty!', NULL, 0, 10, 0, 1, 1, 0, 1, 5, 2, 0, 0, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(2, 'cigar', 'Cigar', 'Consumable', 'Be the boss, and smoke one of these fine brands!', NULL, 0, 50, 0, 1, 1, 0, 0, -5, -15, -8, -15, 30, 0, 0, 0, NULL, NULL, NULL),
	(3, 'cigarette', 'Cigarette', 'Consumable', 'Back in the day, they thought this was healty! For Sure!', NULL, 0, 100, 0, 1, 1, 0, 0, -5, -15, -5, -13, 25, 0, 0, 0, NULL, NULL, NULL),
	(4, 'cigarette_box', 'Cigarette Box', 'Consumable', 'A box containing 25 cigarettes', 'cigarette', 25, 5, 0, 1, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 'coffee', 'Coffee', 'Consumable', 'That mornig brew you can\'t go without', NULL, 0, 5, 0, 1, 1, 0, 1, -10, 20, 3, 20, 20, 10, 30, 60, '{"Anim":"DRINK_COFFEE_HOLD", "Prop":"P_MUGCOFFEE01X", "PropPos":"P_MUGCOFFEE01X_PH_R_HAND"}', NULL, NULL),
	(6, 'egg', 'Eggs', 'Consumable', 'I think it has something to do with a chicken? hmmmm', NULL, 0, 50, 0, 1, 1, 0, 1, 5, -5, 3, 4, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(7, 'egg_box', 'Egg Box', 'Consumable', 'A box containing 10 eggs', 'eggs', 10, 3, 0, 1, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(8, 'gold_bar', 'Goldbar', 'Valuta', 'That mineral that everyone is killing each other for, but then refined into a golden bar', 'gold_coin', 35, 3, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 'gold_nugget', 'Gold Nugget', 'Mineral', 'Unrefined golden nuggest. Don\'t you wish yours where of gold?', NULL, 0, 120, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 'gold_coin', 'Gold Coin', 'Valuta', 'A thing you pay with, but you don\'t want to pay with. Its way to shiny to give away', NULL, 0, 200, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 'silver_nugget', 'Silver Nugget', 'Mineral', 'Unrefined silver nuggest. Seriously, don\'t even bother, gold is much better', 'silver_coin', 50, 200, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 'silver_coin', 'Silver Coin', 'Valuta', 'A thing you pay with, but most also eat with. weird world we live in don\'t you think?', NULL, 0, 200, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 'gold_pan', 'Gold Pan', 'Tool', 'A device to filter gold nuggest out of the water and dirt', NULL, 0, 2, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 'horsebrush', 'Horse Brush', 'Tool', 'A simple tool to keep your horse from getting dirty. Soooo Dirty!!!', NULL, 0, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 'lockpick', 'Lock Pick', 'Tool', 'For those that do not value other people belongings, then this is your tool!', NULL, 0, 5, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 'meat_cooked', 'Cooked Meat', 'Consumable', 'That food that make men become beasts. Just throw the meat to them and then RUN!', NULL, 0, 10, 0, 1, 1, 0, 1, 30, -10, 10, 25, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(17, 'meat_uncooked', 'Uncooked Meat', 'Consumable', 'It\'s meat, it\'s uncooked! You should try to eat it, maybe you wound die from it!', 'meat_cooked', 1, 10, 0, 1, 1, 0, 1, 15, -20, -25, 12, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(18, 'water_clean', 'Clean Water', 'Consumable', 'Around 80% of your body is made out of water, at least that is what the future people whisper in my ears.', NULL, 0, 10, 0, 1, 1, 0, 1, 0, 20, 0, 0, 0, 0, 0, 0, '{"Anim":"DRINK_BOTTLE@Bottle_Cylinder_D1-3_H30-5_Neck_A13_B2-5_CHUG_TRANS", "Prop":"p_bottleJD01x", "PropPos":"p_bottleJD01x_ph_r_hand"}', NULL, NULL),
	(19, 'water_dirty', 'Dirty Water', 'Consumable', 'Cook it before your drink it!', 'water_clean', 1, 10, 0, 1, 1, 0, 1, 0, 20, -10, 0, 0, 0, 0, 0, '{"Anim":"DRINK_BOTTLE@Bottle_Cylinder_D1-3_H30-5_Neck_A13_B2-5_CHUG_TRANS", "Prop":"p_bottleJD01x", "PropPos":"p_bottleJD01x_ph_r_hand"}', NULL, NULL),
	(20, 'campfire', 'Campfire', 'Deployable', 'Something to keep you warm at night. If you had a girlfriend, you\'ve would not need one!', NULL, 0, 2, 1, 1, 1, 0, 1, -5, -10, 0, -20, 0, 0, 0, 0, '{"Anim":"WORLD_HUMAN_CROUCH_INSPECT", "Time":13000, "Prop":"p_campfire02x"}', NULL, NULL),
	(21, 'whiskey', 'Whiskey', 'Consumable', 'Try to drink this, and walk in a strait line to your horse. I dare you!', NULL, 0, 10, 0, 1, 1, 0, 1, -10, -15, 10, -15, 60, 60, 0, 0, '{"Anim":"DRINK_BOTTLE@Bottle_Cylinder_D1-3_H30-5_Neck_A13_B2-5_CHUG_TRANS", "Prop":"p_bottleJD01x", "PropPos":"p_bottleJD01x_ph_r_hand"}', NULL, NULL),
	(22, 'blueberry', 'Blueberry', 'Consumable', 'Its a berry that is not red, but blue!', NULL, 0, 500, 0, 1, 1, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(23, 'blackberry', 'Blackberry', 'Consumable', 'Its a berry that is not blue, but black!', NULL, 0, 500, 0, 1, 1, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(24, 'apple', 'Apple', 'Consumable', 'Oh Oh Adam, what did you do!', NULL, 0, 150, 0, 1, 1, 0, 1, 5, 5, 5, 5, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(25, 'orange', 'Orange', 'Consumable', 'In the old days it was a fruit. In the future, they call it Donald Trump', NULL, 0, 150, 0, 1, 1, 0, 1, 5, 10, 5, 5, 0, 0, 0, 0, '{"Anim":"EAT_MULTI_BITE_FOOD_SPHERE_D8-2_SANDWICH_QUICK_LEFT_HAND"}', NULL, NULL),
	(26, 'trumpet', 'Trumpet', 'Instrument', 'Its from brass, its annoying, don\'t buy it, don\'t play it!', NULL, 0, 1, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Anim":"WORLD_HUMAN_TRUMPET"}', '{"Type":"Client", "Event":"DokuCore:ScriptBundle:Trumpet:Play"}', NULL),
	(27, 'scratchcard', 'Scratch Card', 'Consumable', 'Everyone could be a winner!', NULL, 0, 10, 0, 1, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:ScratchCards:Show:Random", "Delete":true}', NULL),
	(30, 'scratchprize', 'Scratch Winning Card', 'Consumable', 'A winning scratch card', NULL, 0, 10, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:ScratchCards:Get:Rewards"}', NULL),
	(31, 'rowboat', 'Row Boat', 'Boat', 'At least it stays afloat', NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{ "CanSell":"true", "CanBuy":"true", "SellPrice":10.0, "BuyPrice":15.0 }'),
	(32, 'rowboatSwamp', 'Swamp Row Boat', 'Boat', 'You\'re at least safe from Aligators haha', NULL, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{ "CanSell":"true", "CanBuy":"true", "SellPrice":15.0, "BuyPrice":30.0 }'),
	(34, 'chanterelles', 'Chanterelles', 'Herbs', '--', NULL, 0, 100, 0, 1, 1, 0, 0, 7, -10, -20, 20, 30, 30, 30, 30, NULL, NULL, NULL),
	(35, 'currant', 'Currant', 'Herbs', '--', NULL, 0, 100, 0, 1, 1, 0, 0, -10, -20, 10, 10, 0, 0, 0, 0, NULL, NULL, NULL),
	(36, 'oregano', 'Oregano', 'Herbs', '--', NULL, 0, 100, 0, 1, 1, 0, 0, 0, -15, 15, 0, 0, 0, 0, 0, NULL, NULL, NULL),
	(37, 'wintergreen_berry', 'Wintergreen Berry', 'Consumable', '--', NULL, 0, 100, 0, 1, 1, 0, 0, 5, 9, 2, 5, 0, 0, 0, 0, NULL, NULL, NULL),
	(38, 'vanilla_flower', 'Vanilla Flower', 'Herbs', '--', NULL, 0, 100, 0, 1, 1, 0, 0, 3, -7, 7, 15, 10, 20, 10, 20, NULL, NULL, NULL),
	(39, 'evergreen_huckleberry', 'Evergreen Huckleberry', 'Herbs', '--', NULL, 0, 100, 0, 1, 1, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, NULL, NULL, NULL),
	(40, 'weapon_revolver_cattleman', 'Cattleman Revolver', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(41, 'weapon_revolver_doubleaction', 'Double Action Revolver', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(42, 'weapon_repeater_carbine', 'Carbine Repeater', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(43, 'weapon_repeater_winchester', 'Winchester Repeater', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(44, 'weapon_repeater_evans', 'Evans Repeater', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(45, 'weapon_repeater_henry', 'Henry Repeater', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(46, 'weapon_rifle_varmint', 'Varmint Rifle', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(47, 'weapon_rifle_springfield', 'Springfield Rifle', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(48, 'weapon_rifle_boltaction', 'Boltaction Rifle', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(49, 'weapon_sniperrifle_rollingblock', 'Rollingback Sniper', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(50, 'weapon_sniperrifle_carcano', 'Carcano Sniper', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(51, 'weapon_shotgun_sawedoff', 'Saweoff Shotgun', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(52, 'weapon_shotgun_doublebarrel', 'Double Barrel Shotgun', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(53, 'weapon_shotgun_pump', 'Pump Action Shotgun', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(54, 'weapon_shotgun_repeating', 'Repeater Shotgun', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(55, 'weapon_bow', 'Bow', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(56, 'weapon_revolver_schofield', 'Schofield Revolver', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(57, 'weapon_revolver_lemat', 'Lemat  Revolver', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(58, 'weapon_pistol_volcanic', 'Volcanic  Revolver', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(59, 'weapon_pistol_mauser', 'Mauser Pistol', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(60, 'weapon_pistol_semiauto', 'Semi Automatic Pistol', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Secondary"}', NULL),
	(61, 'weapon_shotgun_semiauto', 'Semi Automatic Shotgun', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Primary"}', NULL),
	(62, 'weapon_melee_hatchet', 'Hatchet', 'Tool', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:Tools:Equipt"}', NULL),
	(63, 'weapon_melee_knife', 'Knife', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Melee"}', NULL),
	(64, 'weapon_melee_machete', 'Machete', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Melee"}', NULL),
	(65, 'weapon_lasso', 'Lasso', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Throwable"}', NULL),
	(66, 'weapon_thrown_throwing_knives', 'Throwing Knives', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Throwable"}', NULL),
	(67, 'weapon_thrown_tomahawk', 'Throwing Tomahawk', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Throwable"}', NULL),
	(68, 'weapon_thrown_dynamite', 'Throwing Dynamite', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Throwable"}', NULL),
	(69, 'weapon_thrown_molotov', 'Throwing Molotov', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Throwable"}', NULL),
	(70, 'weapon_melee_lantern', 'Lantern', 'Tool', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:Tools:Equipt"}', NULL),
	(71, 'weapon_melee_broken_sword', 'Broken Sword', 'Weapon', '--', NULL, 0, 5, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:GunStore:Weapon:Equipt", "wType":"Melee"}', NULL),
	(72, 'log', 'Wood Log', 'Mineral', 'A log chopped from a tree', 'lumber', 4, 5, 0, 1, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(73, 'lumber', 'Lumber', 'Mineral', 'Chop a log and you get lumber!', NULL, 0, 10, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(74, 'bark', 'Tree Bark', 'Mineral', 'The skin of the tree', NULL, 0, 30, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(75, 'treesap', 'Tree Sap', 'Mineral', 'Sap from a tree', NULL, 0, 50, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(76, 'stick', 'Tree Stick', 'Mineral', 'A stick from a tree', NULL, 0, 30, 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(77, 'weapon_fishingrod', 'Fishing Rod', 'Tool', 'A stick with a rope and bait....', NULL, 0, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(78, 'fishingbait', 'Fishing Bait', 'Consumable', 'Biat to lure the fish', NULL, 0, 1, 0, 0, 1, 0, 0, 5, -5, -5, 5, 0, 0, 0, 0, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(79, 'fishsmall_uncooked', 'Small Fish Uncooked', 'Consumable', 'a small fish', NULL, 0, 1, 0, 0, 1, 0, 0, 5, -5, -5, 5, 0, 0, 0, 0, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(80, 'fishmedium_uncooked', 'Medium Fish Uncooked', 'Consumable', 'a medium fish', NULL, 0, 1, 0, 0, 1, 0, 0, 5, -5, -5, 5, 0, 0, 0, 0, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL),
	(81, 'fishlarge_uncooked', 'Large Fish Uncooked', 'Consumable', 'a large fish', NULL, 0, 1, 0, 0, 1, 0, 0, 5, -5, -5, 5, 0, 0, 0, 0, NULL, '{"Type":"Client", "Event":"DokusCore:UsableItems:ItemNoUse"}', NULL);
/*!40000 ALTER TABLE `_items` ENABLE KEYS */;

-- Dumping structure for table dokuscore._stores
CREATE TABLE IF NOT EXISTS `_stores` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Item` varchar(50) NOT NULL,
  `Name` varchar(50) NOT NULL DEFAULT '--',
  `Type` varchar(50) DEFAULT '--',
  `Description` longtext DEFAULT '--',
  `Limit` int(11) NOT NULL DEFAULT 25,
  `Buy` float NOT NULL DEFAULT 0.1,
  `Sell` float NOT NULL DEFAULT 0.05,
  `ItemData` longtext DEFAULT '--',
  `Stock` longtext DEFAULT '--',
  `Stores` longtext DEFAULT '--',
  `Taxation` longtext DEFAULT '--',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- Dumping data for table dokuscore._stores: ~23 rows (approximately)
/*!40000 ALTER TABLE `_stores` DISABLE KEYS */;
INSERT INTO `_stores` (`ID`, `Item`, `Name`, `Type`, `Description`, `Limit`, `Buy`, `Sell`, `ItemData`, `Stock`, `Stores`, `Taxation`) VALUES
	(1, 'carrot', 'Carrot', 'Consumable', 'Its orange! Its healty!', 100, 0.02, 0.01, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(2, 'cigar', 'Cigar', 'Consumable', 'Be the boss, and smoke one of these fine brands!', 50, 0.08, 0.03, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(3, 'cigarette', 'Cigarette', 'Consumable', 'Back in the day, they thought this was healty! For Sure!', 50, 0.06, 0.02, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(4, 'cigarette_box', 'Cigarette Box', 'Consumable', 'A box containing 25 cigarettes', 50, 1.7, 1, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(5, 'coffee', 'Coffee', 'Consumable', 'That mornig brew you can\'t go without', 75, 0.1, 0.05, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(6, 'egg', 'Eggs', 'Consumable', 'I think it has something to do with a chicken? hmmmm', 100, 0.02, 0.01, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(7, 'egg_box', 'Egg Box', 'Consumable', 'A box containing 10 eggs', 25, 0.22, 0.1, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(8, 'gold_pan', 'Gold Pan', 'Tool', 'A device to filter gold nuggest out of the water and dirt', 10, 5.75, 2.35, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(9, 'meat_cooked', 'Cooked Meat', 'Consumable', 'That food that make men become beasts. Just throw the meat to them and then RUN!', 75, 0.35, 0.15, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(10, 'water_clean', 'Clean Water', 'Consumable', 'Around 80% of your body is made out of water, at least that is what the future people whisper in my ears.', 35, 0.17, 0.09, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(11, 'whiskey', 'Whiskey', 'Consumable', 'Try to drink this, and walk in a strait line to your horse. I dare you!', 50, 1.2, 0.6, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(12, 'blueberry', 'Blueberry', 'Consumable', 'Its a berry that is not red, but blue!', 100, 0.02, 0.01, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(13, 'blackberry', 'Blackberry', 'Consumable', 'Its a berry that is not blue, but black!', 100, 0.02, 0.01, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(14, 'apple', 'Apple', 'Consumable', 'Oh Oh Adam, what did you do!', 80, 0.04, 0.02, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(15, 'orange', 'Orange', 'Consumable', 'In the old days it was a fruit. In the future, they call it Donald Trump', 25, 0.17, 0.08, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(16, 'trumpet', 'Trumpet', 'Instrument', 'Its from brass, its annoying, don\'t buy it, don\'t play it!', 10, 12.75, 5.7, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"bTax":0,"sTax":0,"Store":"Valentine"},{"bTax":0,"sTax":0,"Store":"SaintDenis"},{"bTax":0,"sTax":0,"Store":"Blackwater"},{"bTax":0,"sTax":0,"Store":"Tumbleweed"},{"bTax":0,"sTax":0,"Store":"Rhodes"},{"bTax":0,"sTax":0,"Store":"Armadillo"},{"bTax":0,"sTax":0,"Store":"Strawberry"}]'),
	(17, 'vanilla_flower', 'Vanilla Flower', 'Herbs', '--', 75, 0.2, 0.08, '[{"Buy":0.02,"Store":"Valentine","Sell":0.01},{"Buy":0.02,"Store":"SaintDenis","Sell":0.01},{"Buy":0.02,"Store":"Blackwater","Sell":0.01},{"Buy":0.02,"Store":"Tumbleweed","Sell":0.01},{"Buy":0.02,"Store":"Rhodes","Sell":0.01},{"Buy":0.02,"Store":"Armadillo","Sell":0.01},{"Buy":0.02,"Store":"Strawberry","Sell":0.01}]', '[{"Store":"Valentine","Stock":100},{"Store":"SaintDenis","Stock":100},{"Store":"Blackwater","Stock":100},{"Store":"Tumbleweed","Stock":100},{"Store":"Rhodes","Stock":100},{"Store":"Armadillo","Stock":100},{"Store":"Strawberry","Stock":100}]', '[{"Buy":true,"Store":"Valentine","Sell":true},{"Buy":true,"Store":"SaintDenis","Sell":true},{"Buy":true,"Store":"Blackwater","Sell":true},{"Buy":true,"Store":"Tumbleweed","Sell":true},{"Buy":true,"Store":"Rhodes","Sell":true},{"Buy":true,"Store":"Armadillo","Sell":true},{"Buy":true,"Store":"Strawberry","Sell":true}]', '[{"sTax":0,"Store":"Valentine","bTax":0},{"sTax":0,"Store":"SaintDenis","bTax":0},{"sTax":0,"Store":"Blackwater","bTax":0},{"sTax":0,"Store":"Tumbleweed","bTax":0},{"sTax":0,"Store":"Rhodes","bTax":0},{"sTax":0,"Store":"Armadillo","bTax":0},{"sTax":0,"Store":"Strawberry","bTax":0}]'),
	(20, 'axe', 'Chopping Axe', 'Tool', 'For chopping those trees', 25, 1.5, 0.7, '[{"Buy":0.02,"Store":"Valentine","Sell":0.01},{"Buy":0.02,"Store":"SaintDenis","Sell":0.01},{"Buy":0.02,"Store":"Blackwater","Sell":0.01},{"Buy":0.02,"Store":"Tumbleweed","Sell":0.01},{"Buy":0.02,"Store":"Rhodes","Sell":0.01},{"Buy":0.02,"Store":"Armadillo","Sell":0.01},{"Buy":0.02,"Store":"Strawberry","Sell":0.01}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Store":"Valentine","Sell":true},{"Buy":true,"Store":"SaintDenis","Sell":true},{"Buy":true,"Store":"Blackwater","Sell":true},{"Buy":true,"Store":"Tumbleweed","Sell":true},{"Buy":true,"Store":"Rhodes","Sell":true},{"Buy":true,"Store":"Armadillo","Sell":true},{"Buy":true,"Store":"Strawberry","Sell":true}]', '[{"Store":"Valentine","sTax":0,"bTax":0},{"Store":"SaintDenis","sTax":0,"bTax":0},{"Store":"Blackwater","sTax":0,"bTax":0},{"Store":"Tumbleweed","sTax":0,"bTax":0},{"Store":"Rhodes","sTax":0,"bTax":0},{"Store":"Armadillo","sTax":0,"bTax":0},{"Store":"Strawberry","sTax":0,"bTax":0}]'),
	(22, 'fishsmall_uncooked', 'Small Fish Uncooked', 'Consumable', 'a small fish', 25, 0.08, 0.05, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"sTax":0,"bTax":0,"Store":"Valentine"},{"sTax":0,"bTax":0,"Store":"SaintDenis"},{"sTax":0,"bTax":0,"Store":"Blackwater"},{"sTax":0,"bTax":0,"Store":"Tumbleweed"},{"sTax":0,"bTax":0,"Store":"Rhodes"},{"sTax":0,"bTax":0,"Store":"Armadillo"},{"sTax":0,"bTax":0,"Store":"Strawberry"}]'),
	(23, 'fishmedium_uncooked', 'Medium Fish Uncooked', 'Consumable', 'a medium fish', 25, 0.12, 0.08, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"sTax":0,"bTax":0,"Store":"Valentine"},{"sTax":0,"bTax":0,"Store":"SaintDenis"},{"sTax":0,"bTax":0,"Store":"Blackwater"},{"sTax":0,"bTax":0,"Store":"Tumbleweed"},{"sTax":0,"bTax":0,"Store":"Rhodes"},{"sTax":0,"bTax":0,"Store":"Armadillo"},{"sTax":0,"bTax":0,"Store":"Strawberry"}]'),
	(24, 'fishlarge_uncooked', 'Large Fish Uncooked', 'Consumable', 'a large fish', 25, 0.15, 0.1, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"sTax":0,"bTax":0,"Store":"Valentine"},{"sTax":0,"bTax":0,"Store":"SaintDenis"},{"sTax":0,"bTax":0,"Store":"Blackwater"},{"sTax":0,"bTax":0,"Store":"Tumbleweed"},{"sTax":0,"bTax":0,"Store":"Rhodes"},{"sTax":0,"bTax":0,"Store":"Armadillo"},{"sTax":0,"bTax":0,"Store":"Strawberry"}]'),
	(25, 'fishingbait', 'Fishing Bait', 'Consumable', 'Biat to lure the fish', 25, 0.02, 0.01, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"sTax":0,"bTax":0,"Store":"Valentine"},{"sTax":0,"bTax":0,"Store":"SaintDenis"},{"sTax":0,"bTax":0,"Store":"Blackwater"},{"sTax":0,"bTax":0,"Store":"Tumbleweed"},{"sTax":0,"bTax":0,"Store":"Rhodes"},{"sTax":0,"bTax":0,"Store":"Armadillo"},{"sTax":0,"bTax":0,"Store":"Strawberry"}]'),
	(26, 'weapon_fishingrod', 'Fishing Rod', 'Tool', 'A stick with a rope and bait....', 25, 1.5, 0.45, '[{"Sell":0.01,"Buy":0.02,"Store":"Valentine"},{"Sell":0.01,"Buy":0.02,"Store":"SaintDenis"},{"Sell":0.01,"Buy":0.02,"Store":"Blackwater"},{"Sell":0.01,"Buy":0.02,"Store":"Tumbleweed"},{"Sell":0.01,"Buy":0.02,"Store":"Rhodes"},{"Sell":0.01,"Buy":0.02,"Store":"Armadillo"},{"Sell":0.01,"Buy":0.02,"Store":"Strawberry"}]', '[{"Stock":100,"Store":"Valentine"},{"Stock":100,"Store":"SaintDenis"},{"Stock":100,"Store":"Blackwater"},{"Stock":100,"Store":"Tumbleweed"},{"Stock":100,"Store":"Rhodes"},{"Stock":100,"Store":"Armadillo"},{"Stock":100,"Store":"Strawberry"}]', '[{"Buy":true,"Sell":true,"Store":"Valentine"},{"Buy":true,"Sell":true,"Store":"SaintDenis"},{"Buy":true,"Sell":true,"Store":"Blackwater"},{"Buy":true,"Sell":true,"Store":"Tumbleweed"},{"Buy":true,"Sell":true,"Store":"Rhodes"},{"Buy":true,"Sell":true,"Store":"Armadillo"},{"Buy":true,"Sell":true,"Store":"Strawberry"}]', '[{"sTax":0,"bTax":0,"Store":"Valentine"},{"sTax":0,"bTax":0,"Store":"SaintDenis"},{"sTax":0,"bTax":0,"Store":"Blackwater"},{"sTax":0,"bTax":0,"Store":"Tumbleweed"},{"sTax":0,"bTax":0,"Store":"Rhodes"},{"sTax":0,"bTax":0,"Store":"Armadillo"},{"sTax":0,"bTax":0,"Store":"Strawberry"}]');
/*!40000 ALTER TABLE `_stores` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
